# The global section has parameters that apply globally to the relayer operation.
[global]
# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'info'
[mode]

[mode.clients]

enabled = true
refresh = true
misbehaviour = false


[mode.connections]
enabled = false

# Specify the channels mode.
[mode.channels]
enabled = false

# Specify the packets mode.
[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]

# Whether or not to enable the REST service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the RESTful
# API requests. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the restful API
# requests. Default: 3000
port = 3000


# The telemetry section defines parameters for Hermes' built-in telemetry capabilities.
# https://hermes.informal.systems/telemetry.html
[telemetry]

# Whether or not to enable the telemetry service. Default: false
enabled = false

# Specify the IPv4/6 host over which the built-in HTTP server will serve the metrics
# gathered by the telemetry service. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the metrics gathered
# by the telemetry service. Default: 3001
port = 3001


# A chains section includes parameters related to a chain and the full node to which
# the relayer can send transactions and queries.
[[chains]]
id = 'local-1'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '1s'
account_prefix = 'juno'
key_name = 'default'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 500000
max_gas = 40000000
gas_price = { price = 0.01, denom = 'ujuno' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '120s'
max_block_time = '1s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''

[[chains]]
id = 'local-2'
rpc_addr = 'http://localhost:36657'
grpc_addr = 'http://localhost:8090'
websocket_addr = 'ws://localhost:36657/websocket'
rpc_timeout = '1s'
account_prefix = 'juno'
key_name = 'default'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 500000
max_gas = 40000000
gas_price = { price = 0.01, denom = 'ujuno' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '120s'
max_block_time = '3s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''

# Mainnet
# [[chains]]
# id = 'juno-1'
# rpc_addr = 'https://juno-rpc.reece.sh:443'
# grpc_addr = 'http://15.204.143.232:9090'
# websocket_addr = 'ws://15.204.143.232:26657/websocket'
# rpc_timeout = '1s'
# account_prefix = 'juno'
# key_name = 'default'
# address_type = { derivation = 'cosmos' }
# store_prefix = 'ibc'
# default_gas = 500000
# max_gas = 4000000
# gas_price = { price = 0.003, denom = 'ujuno' }
# gas_multiplier = 1.1
# max_msg_num = 30
# max_tx_size = 2097152
# clock_drift = '120s'
# max_block_time = '7s'
# trusting_period = '1days'
# trust_threshold = { numerator = '1', denominator = '3' }
# memo_prefix = ''
